# Market Data Service Configuration
quarkus.http.port=8081
quarkus.grpc.server.port=9001

# Redis Configuration
# Defaults to localhost:6379, will be overridden in OCP via environment variables
quarkus.redis.hosts=redis://localhost:6379

# OpenTelemetry configuration
quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://jaeger-collector:4317

# MicroProfile Health
quarkus.smallrye-health.root-path=/health
