# Gateway Service Configuration
quarkus.http.port=8080
quarkus.grpc.server.port=9000

# gRPC Client Configurations
quarkus.grpc.clients.market.host=localhost
quarkus.grpc.clients.market.port=9001
quarkus.grpc.clients.analytics.host=localhost
quarkus.grpc.clients.analytics.port=9002
quarkus.grpc.clients.history.host=localhost
quarkus.grpc.clients.history.port=9003

# OpenTelemetry configuration
quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://jaeger-collector:4317

# GraphQL Configuration
quarkus.smallrye-graphql.path=/graphql
quarkus.smallrye-graphql.ui.enable=true
